name: Update README with images and scripts.

on:
  push:
    branches:
      - main          # Only run on main branch
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write     # Needed to push changes back to the repository

# Prevent multiple workflow runs from interfering with each other
concurrency:
  group: update-readme-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'  # Cache pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run Python script to update README
        run: python README-creater.py

      # Only run if found changes
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Update README with new scripts and images"
            git push
          else
            echo "No changes to commit. Skipping commit and push."
          fi