name: Update README with images and scripts.

on:
  push:
    paths:
      - "plots/**"  # Trigger when images are added or updated
      - "*.py"      # Trigger when Python scripts are added or updated
      - "*.R"       # Trigger when R scripts are added or updated

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python script to update README
        run: python README-creater.py

      # Check for changes
      - name: Check for changes
        id: check-changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes detected."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      # Only run if found changes
      - name: Commit and push changes
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with new images and scripts"
          git push
