name: Update README with images and scripts.

on:
  push:
    branches: [ main ]  # Only run on main branch
    paths:
      - "plots/**"  # Trigger when images are added or updated
      - "*.py"      # Trigger when Python scripts are added or updated
      - "*.R"       # Trigger when R scripts are added or updated
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write  # Needed to push changes back to the repository

# Prevent multiple workflow runs from interfering with each other
concurrency:
  group: update-readme-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'  # Cache pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run Python script to update README
        run: python README-creater.py

      # Check for changes
      - name: Check for changes
        id: check-changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes detected."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      # Only run if found changes
      - name: Commit and push changes
        if: steps.check-changes.outputs.has_changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update README with new images and scripts [skip ci]"
          git push
